import 'dart:ui';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

Color appColorPrimary = Colors.teal;
Color appColorAccent = appColorPrimary.withOpacity(0.3);


TextStyle myTextStyle(myContext ,{Color clr = Colors.white , int ratioSize=14 , bool wantShadow=false , family = 'cairo'})=> TextStyle(
    fontSize: MediaQuery.textScaleFactorOf(myContext)*ratioSize ,
    color: clr,
    fontFamily: family,
    shadows: wantShadow? [Shadow(blurRadius: 10 , color: clr==Colors.black ? Colors.yellow[700] : Colors.black)] : null,
    fontWeight: FontWeight.bold
);

errorBox(context , {isEnterNet=false}){
  return Column(
    mainAxisAlignment: MainAxisAlignment.center,
    children: <Widget>[
      Icon(Icons.error_outline ,color: Colors.red,size: MediaQuery.textScaleFactorOf(context)*40,),
      Text(isEnterNet==false ? 'Sorry, We cannot access servers' : 'check enternet and try again',
        style: myTextStyle(context ,ratioSize: 20).copyWith(fontWeight: FontWeight.normal ,
          shadows: [BoxShadow(blurRadius: 5 ,spreadRadius: 20,color: Colors.white)],
        ),)
    ],
  );
}

const String  aljazeeraImg = 'https://www.ifj.org/fileadmin/news_import/Al_Jazeera_newspaper.jpg';
const String  googleNewsImg = 'https://1.bp.blogspot.com/-_2vlLuCWuus/XS0oOMCgk1I/AAAAAAAAQwM/EL-qB9NkZ04Iu5VWMOxHf4vnxTN7LlIyQCLcBGAs/s1600/google-news.jpg';
const String  errorImg = 'https://scontent.xx.fbcdn.net/v/t1.15752-0/p206x206/142479359_477519313236996_8348429448288179536_n.png?_nc_cat=110&ccb=2&_nc_sid=58c789&_nc_ohc=X4pLhzmroSkAX-QkO4B&_nc_ad=z-m&_nc_cid=0&_nc_ht=scontent.xx&_nc_tp=30&oh=07e609ce79c68f71c8a9cb13e6f75dae&oe=60362510';

List<String> governorates_countries =[
  'Alexandria' ,
  'Aswan' ,
  'Asyut',
  'Beheira' ,
  'Beni Suef' ,
  'Cairo' ,
  'Mansoura,egypt' ,
  'Damietta' ,
  'Faiyum' ,
  'Gharbia' ,
  'Giza' ,
  'Ismailia' ,
  'Kafr El Sheikh' ,
  'Luxor' ,
  'Marsa Matruh' ,
  'Minya, Egypt' ,
  'Monufia' ,
  'Al Wadi al Jadid' ,
  'Shamal Sina' ,
  'Port Said' ,
  'Qalyub' ,
  'Qena' ,
  'Hurghada' ,
  'Sharqia' ,
  'Sohag' ,
  'South Sinai' ,
  'Suez',


  'Afghanistan' ,
  'Albania' ,
  'Algeria' ,
  'Andorra' ,
  'Angola' ,
  'Antigua and Barbuda' ,
  'Argentina' ,
  'Armenia' ,
  'Australia' ,
  'Austria' ,
  'Azerbaijan' ,
  'Bahamas' ,
  'Bahrain' ,
  'Bangladesh' ,
  'Barbados' ,
  'Belarus' ,
  'Belgium' ,
  'Belize' ,
  'Benin' ,
  'Bhutan' ,
  'Bolivia' ,
  'Bosnia and Herzegovina' ,
  'Botswana' ,
  'Brazil' ,
  'Brunei' ,
  'Bulgaria' ,
  'Burkina Faso' ,
  'Burundi' ,
  'Cabo Verde' ,
  'Cambodia' ,
  'Cameroon' ,
  'Canada' ,
  'Central African Republic' ,
  'Chad' ,
  'Chile' ,
  'China' ,
  'Colombia' ,
  'Comoros' ,
  'Congo' ,
  'Costa Rica' ,
  'Cote d\'Ivoire' ,
  'Croatia' ,
  'Cuba' ,
  'Cyprus' ,
  'czech' ,
  'Denmark' ,
  'Djibouti' ,
  'Dominica' ,
  'Dominican Republic' ,
  'Ecuador' ,
  'Egypt' ,
  'El Salvador' ,
  'Equatorial Guinea' ,
  'Eritrea' ,
  'Estonia' ,
  'Eswatini',
  'Ethiopia' ,
  'Fiji' ,
  'Finland' ,
  'France' ,
  'Gabon' ,
  'Gambia' ,
  'Georgia' ,
  'Germany' ,
  'Ghana' ,
  'Greece' ,
  'Grenada' ,
  'Guatemala' ,
  'Guinea' ,
  'Guinea-Bissau' ,
  'Guyana' ,
  'Haiti' ,
  'Honduras' ,
  'Hungary' ,
  'Iceland' ,
  'India' ,
  'Indonesia' ,
  'Iran' ,
  'Iraq' ,
  'Ireland' ,
  'Italy' ,
  'Jamaica' ,
  'Japan' ,
  'Jordan' ,
  'Kazakhstan' ,
  'Kenya' ,
  'Kiribati' ,
  'Kosovo' ,
  'Kuwait' ,
  'Kyrgyzstan' ,
  'Laos' ,
  'Latvia' ,
  'Lebanon' ,
  'Lesotho' ,
  'Liberia' ,
  'Libya' ,
  'Liechtenstein' ,
  'Lithuania' ,
  'Luxembourg' ,
  'Madagascar' ,
  'Malawi' ,
  'Malaysia' ,
  'Maldives' ,
  'Mali' ,
  'Malta' ,
  'Marshall Islands' ,
  'Mauritania' ,
  'Mauritius' ,
  'Mexico' ,
  'Micronesia' ,
  'Moldova' ,
  'Monaco' ,
  'Mongolia' ,
  'Montenegro' ,
  'Morocco' ,
  'Mozambique' ,
  'Myanmar' ,
  'Namibia' ,
  'Nauru' ,
  'Nepal' ,
  'Netherlands' ,
  'New Zealand' ,
  'Nicaragua' ,
  'Niger' ,
  'Nigeria' ,
  'North Korea' ,
  'North Macedonia' ,
  'Norway' ,
  'Oman' ,
  'Pakistan' ,
  'Palau' ,
  'Palestine' ,
  'Panama' ,
  'Papua New Guinea' ,
  'Paraguay' ,
  'Peru' ,
  'Philippines' ,
  'Poland' ,
  'Portugal' ,
  'Qatar' ,
  'Romania' ,
  'Russia' ,
  'Rwanda' ,
  'Saint Kitts and Nevis' ,
  'Saint Lucia' ,
  'Saint Vincent and the Grenadines' ,
  'Samoa' ,
  'San Marino' ,
  'Sao Tome and Principe' ,
  'Saudi Arabia' ,
  'Senegal' ,
  'Serbia' ,
  'Seychelles' ,
  'Sierra Leone' ,
  'Singapore' ,
  'Slovakia' ,
  'Slovenia' ,
  'Solomon Islands' ,
  'Somalia' ,
  'South Africa' ,
  'South Korea' ,
  'South Sudan' ,
  'Spain' ,
  'Sri Lanka' ,
  'Sudan' ,
  'Suriname' ,
  'Sweden' ,
  'Switzerland' ,
  'Syria' ,
  'Taiwan' ,
  'Tajikistan' ,
  'Tanzania' ,
  'Thailand' ,
  'Timor-Leste' ,
  'Togo' ,
  'Tonga' ,
  'Trinidad and Tobago' ,
  'Tunisia' ,
  'Turkey' ,
  'Turkmenistan' ,
  'Tuvalu' ,
  'Uganda' ,
  'Ukraine' ,
  'United Arab Emirates' ,
  'United Kingdom' ,
  'United States' ,
  'Uruguay' ,
  'Uzbekistan' ,
  'Vanuatu' ,
  'Vatican' ,
  'Venezuela' ,
  'Vietnam' ,
  'Yemen' ,
  'Zambia' ,
  'Zimbabwe' ,
];

List governorates_countries_ar =[
  'الإسكندرية' ,
  "أسوان",
  "أسيوط" ,
  "البحيرة",
  "بني سويف",
  "القاهرة",
  'الدقهلية',
  'دمياط',
  "الفيوم",
  "الغربية",
  'الجيزة' ,
  "الإسماعيلية",
  'كفر الشيخ' ,
  "الأقصر",
  'مرسى مطروح',
  'المنيا' ,
  "المنوفية",
  "الوادي الجديد",
  'شمال سيناء',
  'بورسعيد' ,
  'القليوبية' ,
  'قنا',
  'البحر الاحمر' ,
  'الشرقية ',
  'سوهاج',
  "جنوب سيناء",
  "السويس",


  "أفغانستان",
  "ألبانيا",
  'الجزائر' ,
  'أندورا ',
  "أنغولا",
  'أنتيغوا وبربودا' ,
  "الأرجنتين",
  "أرمينيا" ,
  "أستراليا",
  "النمسا",
  "أذربيجان" ,
  'جزر البهاما ',
  'البحرين' ,
  "بنغلاديش",
  "بربادوس" ,
  "بيلاروسيا",
  "بلجيكا",
  "بليز" ,
  "بنين",
  "بوتان" ,
  'بوليفيا',
  'البوسنة والهرسك' ,
  "بوتسوانا",
  'البرازيل' ,
  "بروناي",
  "بلغاريا",
  'بوركينا فاسو' ,
  "بوروندي",
  "كابو فيردي" ,
  "كمبوديا",
  "الكاميرون",
  "كندا",
  'جمهورية افريقيا الوسطى' ,
  "تشاد" ,
  "تشيلي",
  'الصين' ,
  "كولومبيا",
  "جزر القمر",
  "الكونغو" ,
  'كوستا ريكا' ,
  "كوت ديفوار" ,
  "كرواتيا",
  "كوبا",
  "قبرص",
  "التشيك",
  "الدنمارك",
  "جيبوتي",
  "دومينيكا",
  'جمهورية الدومنيكان' ,
  "الإكوادور",
  "مصر",
  'السلفادور' ,
  'غينيا الإستوائية' ,
  "إريتريا" ,
  "إستونيا",
  "إيسواتيني" ,
  "إثيوبيا" ,
  "فيجي" ,
  "فنلندا",
  "فرنسا",
  "الجابون",
  "غامبيا",
  "جورجيا",
  "ألمانيا",
  "غانا",
  'اليونان' ,
  "غرينادا" ,
  "غواتيمالا",
  "غينيا",
  "غينيا بيساو",
  "غيانا" ,
  "هايتي" ,
  "هندوراس",
  'هنغاريا' ,
  "آيسلندا",
  "الهند",
  'إندونيسيا' ,
  "إيران",
  'العراق' ,
  "أيرلندا",
  "إيطاليا",
  "جامايكا",
  "اليابان",
  "الأردن",
  "كازاخستان",
  "كينيا",
  "كيريباتي",
  "كوسوفو",
  'الكويت' ,
  "قيرغيزستان",
  "لاوس" ,
  "لاتفيا",
  "لبنان",
  "ليسوتو" ,
  "ليبيريا",
  "ليبيا" ,
  "ليختنشتاين" ,
  "ليتوانيا",
  "لوكسمبورغ" ,
  "مدغشقر",
  "ملاوي",
  "ماليزيا",
  "جزر المالديف",
  "مالي",
  "مالطا",
  'جزر مارشال ',
  'موريتانيا',
  "موريشيوس",
  "المكسيك" ,
  "ميكرونيزيا",
  "مولدوفا",
  "موناكو",
  'منغوليا',
  "الجبل الأسود",
  'المغرب' ,
  "موزمبيق",
  "ميانمار",
  "ناميبيا",
  'ناورو',
  "نيبال" ,
  'هولندا' ,
  'نيوزيلندا' ,
  'نيكاراغوا' ,
  "النيجر",
  "نيجيريا",
  'كوريا الشماليه' ,
  "مقدونيا الشمالية",
  "النرويج",
  'سلطنة عمان' ,
  "باكستان",
  'بالاو' ,
  'فلسطين ',
  "بنما",
  "بابوا غينيا الجديدة" ,
  "باراغواي",
  "بيرو",
  "الفلبين",
  "بولندا",
  "البرتغال",
  'دولة قطر' ,
  "رومانيا",
  "روسيا",
  "رواندا",
  'سانت كيتس ونيفيس' ,
  'القديسة لوسيا' ,
  'سانت فنسنت وجزر غرينادين' ,
  "ساموا" ,
  'سان مارينو' ,
  "ساو تومي وبرينسيبي" ,
  'المملكة العربية السعودية' ,
  "السنغال",
  "صربيا",
  "سيشل" ,
  'سيرا ليون' ,
  "سنغافورة",
  "سلوفاكيا",
  "سلوفينيا",
  'جزر سليمان' ,
  "الصومال",
  'جنوب أفريقيا' ,
  'كوريا الجنوبية' ,
  'جنوب السودان' ,
  'إسبانيا' ,
  'سيريلانكا' ,
  'السودان' ,
  "سورينام",
  'السويد' ,
  "سويسرا",
  'سوريا' ,
  "تايوان",
  'طاجيكستان',
  "تنزانيا",
  "تايلاند",
  "تيمور الشرقية" ,
  'توجو' ,
  "تونغا",
  'ترينداد وتوباغو' ,
  "تونس",
  'ديك رومي' ,
  "تركمانستان",
  "توفالو" ,
  "أوغندا",
  "أوكرانيا",
  'الإمارات العربية المتحدة' ,
  'المملكة المتحدة' ,
  'الولايات المتحدة الأمريكية' ,
  "أوروغواي",
  "أوزبكستان",
  "فانواتو",
  "الفاتيكان",
  "فنزويلا",
  "فيتنام",
  'اليمن' ,
  "زامبيا",
  "زيمبابوي",
];
